[package]
name = "rquake-win"
version = "0.1.0"
authors = ["Maurice Gilden <MauriceG@gmx.net>"]

[dependencies]
rquake-common = { path = "../rquake-common" }
winapi = "0.2.5"
user32-sys = "0.1.2"
kernel32-sys = "0.2.1"
gdi32-sys = "0.2.0"