[package]
name = "rquake-win"
version = "0.1.0"
authors = ["Maurice Gilden <MauriceG@gmx.net>"]
license = "GPLv2"

[dependencies]
rquake-common = { path = "../rquake-common" }
winapi = "0.2.8"
user32-sys = "0.1.2"
kernel32-sys = "0.2.2"
gdi32-sys = "0.2.0"